### ISSUE TITLE
Cooling thermostat not working

### ISSUE THREAD

**Issue by jaapkoppejan** [Xenomes/Domoticz-TinyTUYA-Plugin#110]
Hello Xenomes,

Thanks again for you great work on developing this Domoticz plugin.  I am using it for a number of sensors and switches.

Recently I purchased a Tuya enabled thermostat that can control the airconditioner via IR. Although the sensors are created in Domoticz, there is no update of values. It concerns the device with ID 'bfbffea7929b18746alk1u' in the attached JSON dump.

Looking forward to you reply!
[dump.json](https://github.com/user-attachments/files/16345555/dump.json)

I am running Domoticz native on a rPi4 bookworm with python 3.12 and version 1.9.2 of the plugin.

Jaap

**Comment by Xenomes** [comment]
Hi Jaap,

Thanks for the json the device control is added on to version 1.9.3

**Comment by jaapkoppejan** [comment]
Hi Xenomes,

Thanks again for your swift response. Now I however get an issue with the re-initialisation. The Domoticz log says:

2024-07-23 20:51:03.857 tinytuya: Scanning for tuya devices on network...
2024-07-23 20:51:04.009 Error: tinytuya: handleThread: PyO3 modules may only be initialized once per interpreter process line 869

I tried to remove the plugin and reinstall it, however without result. Any suggestions?

Jaap

**Comment by Xenomes** [comment]
That is strange, 869 is the point the networkscan is done. looks like the tuya scan is called two times. did you copy the old plugin in the plugin folder?

Ps. added a function, forgot the set temp.

**Comment by jaapkoppejan** [comment]
No, I don't think so. There is only one copy of the plugin. Complete
removal and reinstallation also gives the same result now.

I now get the message:

TinyTUYA: handleThread: PyO3 modules may only be initialized once per
interpreter process line 871

The problem is referred to here as well:
https://github.com/domoticz/domoticz/issues/5717

Op di 23 jul 2024 om 21:35 schreef Xenomes ***@***.***>:

**Comment by Xenomes** [comment]
Did you do a pull only or the full update code?
By running `git checkout 1a2ea2dc0573de7f4f99c7b51eb0830a359aba57` you go back to 1.9.2

**Comment by jaapkoppejan** [comment]
First a git pull only, but when I encountered this issue I decided to also
do a full code update, with removal and reinstallation. This didn't help. I
am thinking it might be associated with my python upgrade from 3.11 to
3.12  yesterday. In order to test this I will first test the setup on
another raspberry pi 3 with Domoticz that is not yet updated. Will let you
know....

Op di 23 jul 2024 22:12 schreef Xenomes ***@***.***>:

**Comment by jaapkoppejan** [comment]
Hello again Xenomes,

Regretfully the plugin is still not working as it should for my thermostat
reported in issue #110. I can provide comments to the thermostat from
Domoticz, but data from the thermostat is not properly received by
Domoticz. The strange thing is that on my network I have both a raspberry
Pi 3 and raspberry Pi 4 with Domoticz and your plugin installed (normally
not operated at the same time to avoid too many requests), and the data
reception capability differs for both as follows:

Raspberry pi 3 (running 1.9.3):
[image: image.png]

Raspberry pi 4 (running 1.9.4):
[image: image.png]

When comparing these two with the attached dump.json (which always fails
the first time, the second time it gives data) I notice that
- the Pi's do not show the same sensor data from the available data (seems
weird)
- some sensor data is received on the Pi3, other sensor data is received on
the Pi4
- some data is missing in both (e.g.  from the humidity sensor)
- the 'Power' switch in Domoticz seems to correspond to the
'infrared_switch' in the json file. I can control this switch from Domoticz
to the Thermostat, but not from the thermostat to both pi's.

Any suggestion what I can do? As all data is correctly entered into the
json file, it seems it should be possible to also get it into Domoticz.

Best regards!!

Jaap


Op di 23 jul 2024 om 20:21 schreef Xenomes ***@***.***>:

**Comment by Xenomes** [comment]
Hi Jaap,
i see the image are missing. Can you email it to xenomes@outlook.com

**Comment by Xenomes** [comment]
>- the Pi's do not show the same sensor data from the available data (seems
weird)
>- some sensor data is received on the Pi3, other sensor data is received on
the Pi4

Data is pulled once time a minute, so data could be different for one minute.

>- some data is missing in both (e.g.  from the humidity sensor)
>- the 'Power' switch in Domoticz seems to correspond to the
'infrared_switch' in the json file. I can control this switch from Domoticz
to the Thermostat, but not from the thermostat to both pi's.

Fixed in  the latest push.

**Comment by jaapkoppejan** [comment]
Hello Xenomes,

Thank you again for this quick action, and sorry something went wrong
uploading the pictures!

With the update the power button now works on both Pi's, and all other data
also seems to be returned to my Pi3. There is however still a problem with
the Pi4, where the actual temperature is not updated and the humidity data
sensor is not shown (it does now appear on the Pi3). You can see the
difference in both screenshots attached.

Strange that this happens, apparently it has to do with the way data is
treated on the Pi4. In case you are also lost, I can do a workaround by
using the pi3 for all data, and making the data available to the Pi4.

Best regards,

Jaap

Op vr 2 aug 2024 om 22:02 schreef Xenomes ***@***.***>:

**Comment by Xenomes** [comment]
Still no screenshots? Try to upload them to GitHub; sending them by email won't work. Whether you're using a Pi 3 or Pi 4 shouldn't matter, but the version of Python could.

**Comment by Xenomes** [comment]
Hi Jaap.
Can you check if the issue on your second system is fix with version 1.9.5? 
Had a similar issue in topic #112, this was a bookworm dirtro with Python 3.11.2. Hopefully it is also fix for Python 3.12.
